### ISSUE TITLE
Prices allow to use scientific notation of 0

### ISSUE THREAD

**Issue by artursmet** [mirumee/prices#13]
There is one corner case, when using decimals.

```python
>>> Decimal('0') / Decimal('0.1')
Decimal('0E+1')
```
Anyway it's zero, but it has different notation.
```python
>>> result = Decimal('0') / Decimal('0.1')
>>> result == Decimal('0')
True
```

It may cause some problems, when we do some divisions and create `Price` from division results.

```python
>>> result = Decimal('0') / Decimal('0.1')
>>> price = Price(result, currency='EUR')
>>> price.net, price.gross
(Decimal('0E+1'), Decimal('0E+1'))
```

**Comment by patrys** [comment]
This is expected. The result of division has precision dependent on its arguments. In this case 0 * 10^1. Use quantisation as needed.
