### ISSUE TITLE
New API and django-prices and django-prices-openexchangerates?

### ISSUE THREAD

**Issue by hetsch** [mirumee/prices#24]
Thank's for this nice packages! I wanted to ask if there are any plans to update django-prices and django-prices-exchangerates to the new 1.0 API?

**Comment by patrys** [comment]
Yes, we're intending to update both and release them as alpha/beta. This in turn will allow us to test the new APIs in Saleor before we release them as stable.

**Comment by hetsch** [comment]
Yeah! Don't wanna be rude but do you have some time estimates? Just roughly ...

**Comment by patrys** [comment]
CC @elwoodxblues as he's in charge of the roadmap

**Comment by elwoodxblues** [comment]
I think we should have it by the end of this month.

**Comment by rafalp** [comment]
`prices`, `django-prices` and `django-prices-openexchangerates` all had their 1.0.0 releases this week and are now working with new API. 🎉
